package aplicacion.modelo.dominio;
// Generated 21/06/2018 01:26:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 *Clasificacions generated by hbm2java
 */
public class Clasificacion  implements java.io.Serializable {


     private Integer claCodigo;
     private String claDescripcion;
     private boolean claEstado;
     private Set pelClas = new HashSet(0);

    public Clasificacion() {
    }

	
    public Clasificacion(String claDescripcion, boolean claEstado) {
        this.claDescripcion = claDescripcion;
        this.claEstado = claEstado;
    }
    public Clasificacion(String claDescripcion, boolean claEstado, Set pelClas) {
       this.claDescripcion = claDescripcion;
       this.claEstado = claEstado;
       this.pelClas = pelClas;
    }
   
    public Integer getClaCodigo() {
        return this.claCodigo;
    }
    
    public void setClaCodigo(Integer claCodigo) {
        this.claCodigo = claCodigo;
    }
    public String getClaDescripcion() {
        return this.claDescripcion;
    }
    
    public void setClaDescripcion(String claDescripcion) {
        this.claDescripcion = claDescripcion;
    }
    public boolean isClaEstado() {
        return this.claEstado;
    }
    
    public void setClaEstado(boolean claEstado) {
        this.claEstado = claEstado;
    }
    public Set getPelClas() {
        return this.pelClas;
    }
    
    public void setPelClas(Set pelClas) {
        this.pelClas = pelClas;
    }




}


